name: Dependabot auto-merge
on:
    workflow_call:

permissions:
    contents: write
    pull-requests: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'TSStudio/blog.tmysam.top' && github.event.pull_request.head.repo.full_name == github.repository
        steps:
            - name: Merge tested Dependabot commit
              run: gh pr merge --merge --match-head-commit "$PR_SHA" "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  PR_SHA: ${{github.event.pull_request.head.sha}}
                  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
